### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mexikoedi** [doodlezucc/ttt_portal_gun#5]
I got a script error recently on my dedicated server while playing TTT2.
Here: 
```
[TTT - Portal Gun for Traitor/Detective] lua/weapons/weapon_portalgun.lua:81: Tried to use a NULL entity! 
1. SetNWEntity - [C]:-1 
2. func - lua/weapons/weapon_portalgun.lua:81 
3. unknown - lua/includes/extensions/net.lua:38
```
I think that there is missing check.

**Comment by doodlezucc** [comment]
Hey there, thanks for the report and sorry for taking this long to answer. 🐌 I've looked into it and according to [the wiki](https://wiki.facepunch.com/gmod/net.ReadEntity), you're right that a validity check is definitely recommended after calling `net.ReadEntity()`. Now on master, shortly available in the workshop :)
